In [3]:
import pandas as pd

In [6]:
df = pd.read_csv("supermarket_sales - Sheet1.csv")

In [7]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [10]:
df.groupby("City").Quantity.sum()

City
Mandalay     1820
Naypyitaw    1831
Yangon       1859
Name: Quantity, dtype: int64

In [13]:
df.coluns()

AttributeError: 'DataFrame' object has no attribute 'coluns'

In [14]:
df.shape

(1000, 17)

In [15]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [17]:
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [18]:
df.City

0         Yangon
1      Naypyitaw
2         Yangon
3         Yangon
4         Yangon
5      Naypyitaw
6         Yangon
7      Naypyitaw
8         Yangon
9       Mandalay
10      Mandalay
11      Mandalay
12        Yangon
13        Yangon
14        Yangon
15      Mandalay
16        Yangon
17        Yangon
18        Yangon
19      Mandalay
20     Naypyitaw
21      Mandalay
22      Mandalay
23        Yangon
24        Yangon
25        Yangon
26      Mandalay
27        Yangon
28      Mandalay
29        Yangon
         ...
970     Mandalay
971     Mandalay
972     Mandalay
973       Yangon
974    Naypyitaw
975     Mandalay
976       Yangon
977     Mandalay
978     Mandalay
979     Mandalay
980    Naypyitaw
981       Yangon
982       Yangon
983    Naypyitaw
984    Naypyitaw
985     Mandalay
986     Mandalay
987     Mandalay
988    Naypyitaw
989     Mandalay
990       Yangon
991     Mandalay
992       Yangon
993     Mandalay
994    Naypyitaw
995    Naypyitaw
996     Mandalay
997       Yangon
998       Yangon
999       Yangon
Name: City, dtype: object

In [20]:
citys = df.City

In [22]:
citys.head(10)

0       Yangon
1    Naypyitaw
2       Yangon
3       Yangon
4       Yangon
5    Naypyitaw
6       Yangon
7    Naypyitaw
8       Yangon
9     Mandalay
Name: City, dtype: object

In [23]:
citys.sum()

'YangonNaypyitawYangonYangonYangonNaypyitawYangonNaypyitawYangonMandalayMandalayMandalayYangonYangonYangonMandalayYangonYangonYangonMandalayNaypyitawMandalayMandalayYangonYangonYangonMandalayYangonMandalayYangonMandalayMandalayMandalayYangonNaypyitawNaypyitawYangonYangonNaypyitawMandalayMandalayNaypyitawMandalayNaypyitawNaypyitawMandalayMandalayMandalayMandalayNaypyitawNaypyitawYangonMandalayNaypyitawMandalayNaypyitawYangonYangonYangonNaypyitawNaypyitawNaypyitawMandalayYangonMandalayYangonNaypyitawMandalayYangonYangonNaypyitawNaypyitawMandalayNaypyitawYangonNaypyitawNaypyitawYangonNaypyitawNaypyitawNaypyitawMandalayNaypyitawNaypyitawNaypyitawNaypyitawNaypyitawYangonYangonMandalayNaypyitawNaypyitawYangonMandalayNaypyitawYangonMandalayNaypyitawYangonMandalayNaypyitawNaypyitawNaypyitawYangonMandalayYangonNaypyitawYangonNaypyitawNaypyitawMandalayNaypyitawMandalayYangonNaypyitawNaypyitawMandalayMandalayYangonMandalayYangonNaypyitawMandalayNaypyitawMandalayYangonYangonNaypyitawNaypyitawMandalayMandalayYangonMandalayMandalayNaypyitawNaypyitawYangonYangonMandalayYangonNaypyitawNaypyitawNaypyitawNaypyitawYangonNaypyitawYangonNaypyitawMandalayYangonMandalayNaypyitawYangonNaypyitawNaypyitawYangonMandalayMandalayMandalayMandalayNaypyitawYangonYangonNaypyitawMandalayMandalayNaypyitawYangonYangonYangonYangonMandalayNaypyitawMandalayMandalayYangonYangonNaypyitawYangonNaypyitawNaypyitawNaypyitawYangonNaypyitawYangonMandalayMandalayMandalayYangonNaypyitawMandalayMandalayNaypyitawMandalayYangonNaypyitawNaypyitawYangonNaypyitawNaypyitawNaypyitawMandalayNaypyitawMandalayMandalayYangonNaypyitawNaypyitawMandalayMandalayYangonNaypyitawMandalayMandalayMandalayYangonMandalayYangonMandalayMandalayMandalayMandalayNaypyitawNaypyitawYangonNaypyitawMandalayNaypyitawMandalayYangonMandalayMandalayMandalayMandalayYangonYangonNaypyitawNaypyitawMandalayYangonYangonYangonNaypyitawYangonMandalayYangonMandalayYangonYangonMandalayMandalayNaypyitawNaypyitawYangonYangonMandalayYangonYangonYangonNaypyitawYangonNaypyitawMandalayYangonMandalayYangonNaypyitawMandalayYangonYangonMandalayNaypyitawYangonYangonMandalayMandalayNaypyitawNaypyitawNaypyitawYangonYangonNaypyitawYangonYangonYangonMandalayNaypyitawNaypyitawMandalayYangonMandalayNaypyitawYangonYangonMandalayNaypyitawNaypyitawYangonYangonNaypyitawNaypyitawMandalayNaypyitawYangonMandalayYangonYangonYangonYangonYangonMandalayNaypyitawYangonYangonNaypyitawNaypyitawNaypyitawNaypyitawNaypyitawNaypyitawNaypyitawNaypyitawYangonYangonYangonMandalayYangonNaypyitawMandalayYangonMandalayYangonYangonYangonNaypyitawYangonYangonMandalayNaypyitawMandalayMandalayMandalayMandalayNaypyitawYangonYangonYangonNaypyitawYangonMandalayNaypyitawYangonMandalayMandalayNaypyitawMandalayNaypyitawNaypyitawMandalayMandalayYangonNaypyitawNaypyitawYangonNaypyitawNaypyitawNaypyitawYangonNaypyitawYangonMandalayMandalayNaypyitawNaypyitawYangonYangonMandalayNaypyitawNaypyitawMandalayYangonNaypyitawMandalayNaypyitawYangonMandalayNaypyitawYangonNaypyitawMandalayNaypyitawMandalayYangonYangonYangonYangonYangonMandalayMandalayMandalayNaypyitawNaypyitawNaypyitawMandalayNaypyitawYangonYangonMandalayYangonNaypyitawMandalayMandalayYangonYangonYangonMandalayNaypyitawNaypyitawMandalayYangonNaypyitawNaypyitawNaypyitawMandalayNaypyitawMandalayYangonMandalayMandalayYangonMandalayNaypyitawYangonMandalayMandalayNaypyitawNaypyitawYangonNaypyitawNaypyitawNaypyitawMandalayYangonNaypyitawYangonMandalayNaypyitawNaypyitawMandalayMandalayMandalayMandalayYangonYangonYangonMandalayMandalayMandalayNaypyitawNaypyitawNaypyitawMandalayNaypyitawNaypyitawYangonNaypyitawNaypyitawMandalayNaypyitawNaypyitawNaypyitawYangonYangonMandalayYangonYangonYangonNaypyitawMandalayYangonNaypyitawNaypyitawYangonMandalayNaypyitawMandalayMandalayYangonNaypyitawMandalayMandalayYangonMandalayNaypyitawMandalayMandalayNaypyitawNaypyitawMandalayYangonMandalayNaypyitawNaypyitawMandalayMandalayYangonMandalayMandalayMandalayNaypyitawMandalayYangonYangonYangonNaypyitawNaypyitawMandalayNaypyitawYangonNaypyitawMandalayNaypyitawYangonNaypyitawYangonYangonMandalayMandalayMandalayYangonYangonYangonMandalayNaypyitawYangonNaypyitawMandalayYangonYangonNaypyitawYangonNaypyitawMandalayNaypyitawMandalayMandalayYangonYangonMandalayYangonMandalayMandalayMandalayNaypyitawYangonMandalayMandalayNaypyitawYangonYangonMandalayNaypyitawMandalayYangonMandalayYangonNaypyitawYangonMandalayNaypyitawMandalayMandalayYangonMandalayYangonMandalayMandalayNaypyitawYangonMandalayNaypyitawYangonNaypyitawMandalayMandalayYangonYangonYangonNaypyitawYangonNaypyitawNaypyitawYangonYangonMandalayMandalayYangonNaypyitawNaypyitawYangonNaypyitawNaypyitawNaypyitawMandalayNaypyitawMandalayYangonNaypyitawYangonMandalayYangonNaypyitawMandalayNaypyitawYangonYangonMandalayNaypyitawYangonNaypyitawYangonYangonMandalayMandalayMandalayMandalayYangonMandalayYangonYangonYangonYangonYangonMandalayMandalayMandalayYangonNaypyitawMandalayMandalayMandalayNaypyitawMandalayNaypyitawNaypyitawYangonNaypyitawMandalayNaypyitawNaypyitawMandalayMandalayYangonMandalayMandalayYangonNaypyitawYangonYangonYangonMandalayNaypyitawMandalayNaypyitawNaypyitawYangonMandalayMandalayNaypyitawMandalayYangonMandalayMandalayNaypyitawYangonMandalayMandalayYangonNaypyitawYangonMandalayMandalayNaypyitawYangonMandalayMandalayMandalayYangonNaypyitawYangonNaypyitawNaypyitawYangonNaypyitawNaypyitawYangonYangonMandalayYangonNaypyitawNaypyitawMandalayMandalayMandalayMandalayMandalayMandalayNaypyitawNaypyitawYangonYangonNaypyitawNaypyitawNaypyitawNaypyitawYangonYangonYangonYangonMandalayMandalayNaypyitawMandalayNaypyitawMandalayNaypyitawNaypyitawMandalayNaypyitawMandalayYangonYangonYangonMandalayMandalayNaypyitawNaypyitawNaypyitawMandalayYangonNaypyitawNaypyitawYangonYangonNaypyitawNaypyitawMandalayNaypyitawMandalayNaypyitawMandalayYangonYangonMandalayNaypyitawYangonMandalayYangonYangonYangonMandalayMandalayYangonYangonYangonMandalayNaypyitawMandalayMandalayYangonMandalayNaypyitawNaypyitawNaypyitawNaypyitawMandalayNaypyitawMandalayNaypyitawMandalayNaypyitawYangonYangonNaypyitawNaypyitawYangonNaypyitawNaypyitawNaypyitawYangonYangonNaypyitawMandalayYangonYangonMandalayNaypyitawYangonMandalayNaypyitawMandalayNaypyitawNaypyitawYangonMandalayYangonYangonYangonMandalayNaypyitawMandalayYangonNaypyitawYangonYangonMandalayNaypyitawYangonMandalayMandalayMandalayYangonNaypyitawYangonMandalayYangonMandalayYangonNaypyitawYangonYangonMandalayMandalayYangonMandalayYangonYangonMandalayNaypyitawNaypyitawYangonMandalayYangonNaypyitawYangonYangonYangonNaypyitawNaypyitawYangonYangonYangonNaypyitawMandalayYangonMandalayMandalayYangonMandalayYangonNaypyitawYangonMandalayMandalayYangonNaypyitawMandalayNaypyitawNaypyitawYangonYangonNaypyitawMandalayYangonYangonNaypyitawNaypyitawMandalayYangonMandalayMandalayNaypyitawMandalayYangonYangonYangonYangonYangonNaypyitawYangonNaypyitawMandalayNaypyitawMandalayMandalayMandalayNaypyitawNaypyitawNaypyitawYangonNaypyitawMandalayYangonYangonNaypyitawNaypyitawNaypyitawMandalayYangonMandalayMandalayNaypyitawYangonYangonYangonNaypyitawNaypyitawYangonMandalayMandalayNaypyitawMandalayNaypyitawNaypyitawNaypyitawMandalayMandalayYangonMandalayMandalayMandalayNaypyitawYangonNaypyitawMandalayNaypyitawNaypyitawYangonYangonNaypyitawYangonNaypyitawYangonYangonYangonYangonNaypyitawMandalayNaypyitawMandalayMandalayMandalayMandalayNaypyitawMandalayYangonNaypyitawMandalayNaypyitawYangonNaypyitawYangonYangonNaypyitawMandalayMandalayYangonYangonYangonMandalayMandalayMandalayMandalayYangonNaypyitawMandalayYangonMandalayMandalayMandalayNaypyitawYangonYangonNaypyitawNaypyitawMandalayMandalayMandalayNaypyitawMandalayYangonMandalayYangonMandalayNaypyitawNaypyitawMandalayYangonYangonYangon'

In [24]:
df.describe()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

In [25]:
df["Total"].sum()

322966.74899999995

In [26]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [30]:
Yagon = df.loc[df["City"] == "Yangon"]

In [31]:
Yagon.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8

In [32]:
len(Yagon)

340

In [34]:
Yagon.shape

(340, 17)

In [47]:
data = df.loc[df["Date"] == "2/25/2019"].loc[data["City"] == "Mandalay"]
data.head()

IndexingError: Unalignable boolean Series key provided

In [40]:
dataMand = data.loc[data["City"] == "Mandalay"]
dataMand.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
30,871-79-8483,B,Mandalay,Normal,Male,Fashion accessories,94.13,5,23.5325,494.1825,2/25/2019,19:39,Credit card,470.65,4.761905,23.5325,4.8
165,505-02-0892,B,Mandalay,Member,Male,Health and beauty,42.57,8,17.0280,357.5880,2/25/2019,14:12,Ewallet,340.56,4.761905,17.0280,5.6
504,511-54-3087,B,Mandalay,Normal,Male,Sports and travel,88.45,1,4.4225,92.8725,2/25/2019,16:36,Credit card,88.45,4.761905,4.4225,9.5
570,834-83-1826,B,Mandalay,Member,Female,Home and lifestyle,82.04,5,20.5100,430.7100,2/25/2019,17:16,Credit card,410.20,4.761905,20.5100,7.6
831,636-17-0325,B,Mandalay,Normal,Male,Health and beauty,62.57,4,12.5140,262.7940,2/25/2019,18:37,Cash,250.28,4.761905,12.5140,9.5

In [42]:
dataMand.shape

(8, 17)

In [43]:
dataMand

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
30,871-79-8483,B,Mandalay,Normal,Male,Fashion accessories,94.13,5,23.5325,494.1825,2/25/2019,19:39,Credit card,470.65,4.761905,23.5325,4.8
165,505-02-0892,B,Mandalay,Member,Male,Health and beauty,42.57,8,17.0280,357.5880,2/25/2019,14:12,Ewallet,340.56,4.761905,17.0280,5.6
504,511-54-3087,B,Mandalay,Normal,Male,Sports and travel,88.45,1,4.4225,92.8725,2/25/2019,16:36,Credit card,88.45,4.761905,4.4225,9.5
570,834-83-1826,B,Mandalay,Member,Female,Home and lifestyle,82.04,5,20.5100,430.7100,2/25/2019,17:16,Credit card,410.20,4.761905,20.5100,7.6
831,636-17-0325,B,Mandalay,Normal,Male,Health and beauty,62.57,4,12.5140,262.7940,2/25/2019,18:37,Cash,250.28,4.761905,12.5140,9.5
853,866-70-2814,B,Mandalay,Normal,Female,Electronic accessories,52.79,10,26.3950,554.2950,2/25/2019,11:58,Ewallet,527.90,4.761905,26.3950,10.0
877,608-05-3804,B,Mandalay,Member,Male,Electronic accessories,39.75,1,1.9875,41.7375,2/25/2019,20:19,Cash,39.75,4.761905,1.9875,6.1
952,574-80-1489,B,Mandalay,Member,Female,Food and beverages,62.85,4,12.5700,263.9700,2/25/2019,13:22,Ewallet,251.40,4.761905,12.5700,8.7

In [48]:
df.loc[df["Customer type"] == "Normal"]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0
12,365-64-0515,A,Yangon,Normal,Female,Electronic accessories,46.95,5,11.7375,246.4875,2/12/2019,10:25,Ewallet,234.75,4.761905,11.7375,7.1
13,252-56-2699,A,Yangon,Normal,Male,Food and beverages,43.19,10,21.5950,453.4950,2/7/2019,16:48,Ewallet,431.90,4.761905,21.5950,8.2
14,829-34-3910,A,Yangon,Normal,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,19:21,Cash,713.80,4.761905,35.6900,5.7
17,765-26-6951,A,Yangon,Normal,Male,Sports and travel,72.61,6,21.7830,457.4430,1/1/2019,10:39,Credit card,435.66,4.761905,21.7830,6.9
18,329-62-1586,A,Yangon,Normal,Male,Food and beverages,54.67,3,8.2005,172.2105,1/21/2019,18:00,Credit card,164.01,4.761905,8.2005,8.6
19,319-50-3348,B,Mandalay,Normal,Female,Home and lifestyle,40.30,2,4.0300,84.6300,3/11/2019,15:30,Ewallet,80.60,4.761905,4.0300,4.4
21,371-85-5789,B,Mandalay,Normal,Male,Health and beauty,87.98,3,13.1970,277.1370,3/5/2019,10:40,Ewallet,263.94,4.761905,13.1970,5.1
22,273-16-6619,B,Mandalay,Normal,Male,Home and lifestyle,33.20,2,3.3200,69.7200,3/15/2019,12:20,Credit card,66.40,4.761905,3.3200,4.4
23,636-48-8204,A,Yangon,Normal,Male,Electronic accessories,34.56,5,8.6400,181.4400,2/17/2019,11:15,Ewallet,172.80,4.761905,8.6400,9.9
26,649-29-6775,B,Mandalay,Normal,Male,Fashion accessories,33.52,1,1.6760,35.1960,2/8/2019,15:31,Cash,33.52,4.761905,1.6760,6.7
27,189-17-4241,A,Yangon,Normal,Female,Fashion accessories,87.67,2,8.7670,184.1070,3/10/2019,12:17,Credit card,175.34,4.761905,8.7670,7.7
28,145-94-9061,B,Mandalay,Normal,Female,Food and beverages,88.36,5,22.0900,463.8900,1/25/2019,19:48,Cash,441.80,4.761905,22.0900,9.6
29,848-62-7243,A,Yangon,Normal,Male,Health and beauty,24.89,9,11.2005,235.2105,3/15/2019,15:36,Cash,224.01,4.761905,11.2005,7.4
30,871-79-8483,B,Mandalay,Normal,Male,Fashion accessories,94.13,5,23.5325,494.1825,2/25/2019,19:39,Credit card,470.65,4.761905,23.5325,4.8
32,640-49-2076,B,Mandalay,Normal,Male,Sports and travel,83.78,8,33.5120,703.7520,1/10/2019,14:49,Cash,670.24,4.761905,33.5120,5.1
33,595-11-5460,A,Yangon,Normal,Male,Health and beauty,96.58,2,9.6580,202.8180,3/15/2019,10:12,Credit card,193.16,4.761905,9.6580,5.1
37,272-65-1806,A,Yangon,Normal,Female,Electronic accessories,60.88,9,27.3960,575.3160,1/15/2019,17:17,Ewallet,547.92,4.761905,27.3960,4.7
38,333-73-7901,C,Naypyitaw,Normal,Female,Health and beauty,54.92,8,21.9680,461.3280,3/23/2019,13:24,Ewallet,439.36,4.761905,21.9680,7.6
54,242-55-6721,B,Mandalay,Normal,Male,Home and lifestyle,16.16,2,1.6160,33.9360,3/7/2019,11:49,Ewallet,32.32,4.761905,1.6160,6.5
55,399-46-5918,C,Naypyitaw,Normal,Female,Electronic accessories,85.98,8,34.3920,722.2320,2/28/2019,19:01,Cash,687.84,4.761905,34.3920,8.2
57,635-40-6220,A,Yangon,Normal,Male,Health and beauty,89.60,8,35.8400,752.6400,2/7/2019,11:28,Ewallet,716.80,4.761905,35.8400,6.6
59,120-06-4233,C,Naypyitaw,Normal,Male,Electronic accessories,30.61,6,9.1830,192.8430,3/12/2019,20:36,Cash,183.66,4.761905,9.1830,9.3
61,803-83-5989,C,Naypyitaw,Normal,Male,Home and lifestyle,55.73,6,16.7190,351.0990,2/24/2019,10:55,Ewallet,334.38,4.761905,16.7190,7.0
66,838-78-4295,C,Naypyitaw,Normal,Female,Health and beauty,33.47,2,3.3470,70.2870,2/10/2019,15:43,Ewallet,66.94,4.761905,3.3470,6.7
68,232-11-3025,A,Yangon,Normal,Male,Sports and travel,78.77,10,39.3850,827.0850,1/24/2019,10:04,Cash,787.70,4.761905,39.3850,6.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,809-69-9497,A,Yangon,Normal,Female,Home and lifestyle,45.68,10,22.8400,479.6400,1/19/2019,19:30,Ewallet,456.80,4.761905,22.8400,5.7
943,449-16-6770,A,Yangon,Normal,Male,Health and beauty,50.79,5,12.6975,266.6475,2/19/2019,14:53,Credit card,253.95,4.761905,12.6975,5.3
945,489-82-1237,A,Yangon,Normal,Female,Electronic accessories,93.88,7,32.8580,690.0180,1/5/2019,11:51,Credit card,657.16,4.761905,32.8580,7.3
949,365-16-4334,B,Mandalay,Normal,Female,Food and beverages,26.43,8,10.5720,222.0120,2/24/2019,14:26,Ewallet,211.44,4.761905,10.5720,8.9
955,846-10-0341,A,Yangon,Normal,Female,Fashion accessories,42.57,7,14.8995,312.8895,1/6/2019,11:51,Cash,297.99,4.761905,14.8995,6.8
957,430-02-3888,B,Mandalay,Normal,Male,Electronic accessories,46.02,6,13.8060,289.9260,2/7/2019,15:55,Cash,276.12,4.761905,13.8060,7.1
958,867-47-1948,C,Naypyitaw,Normal,Female,Home and lifestyle,15.80,10,7.9000,165.9000,1/9/2019,12:07,Cash,158.00,4.761905,7.9000,7.8
962,593-08-5916,A,Yangon,Normal,Female,Fashion accessories,15.50,1,0.7750,16.2750,3/19/2019,15:23,Credit card,15.50,4.761905,0.7750,7.4
964,794-42-3736,B,Mandalay,Normal,Male,Food and beverages,33.33,2,3.3330,69.9930,1/26/2019,14:41,Credit card,66.66,4.761905,3.3330,6.4
965,172-42-8274,B,Mandalay,Normal,Female,Electronic accessories,38.27,2,3.8270,80.3670,3/2/2019,18:18,Credit card,76.54,4.761905,3.8270,5.8
966,558-60-5016,A,Yangon,Normal,Female,Home and lifestyle,33.30,9,14.9850,314.6850,3/4/2019,15:27,Ewallet,299.70,4.761905,14.9850,7.2
968,605-03-2706,A,Yangon,Normal,Female,Health and beauty,15.80,3,2.3700,49.7700,3/25/2019,18:02,Cash,47.40,4.761905,2.3700,9.5
972,452-04-8808,B,Mandalay,Normal,Male,Electronic accessories,87.08,7,30.4780,640.0380,1/26/2019,15:17,Cash,609.56,4.761905,30.4780,5.5
973,531-56-4728,A,Yangon,Normal,Male,Home and lifestyle,80.08,3,12.0120,252.2520,2/11/2019,15:29,Cash,240.24,4.761905,12.0120,5.4
974,744-82-9138,C,Naypyitaw,Normal,Male,Fashion accessories,86.13,2,8.6130,180.8730,2/7/2019,17:59,Cash,172.26,4.761905,8.6130,8.2
976,221-25-5073,A,Yangon,Normal,Female,Food and beverages,74.66,4,14.9320,313.5720,3/4/2019,10:39,Cash,298.64,4.761905,14.9320,8.5
978,156-20-0370,B,Mandalay,Normal,Female,Electronic accessories,25.45,1,1.2725,26.7225,3/10/2019,18:10,Credit card,25.45,4.761905,1.2725,5.1
979,151-33-7434,B,Mandalay,Normal,Female,Food and beverages,67.77,1,3.3885,71.1585,2/4/2019,20:43,Credit card,67.77,4.761905,3.3885,6.5
981,809-46-1866,A,Yangon,Normal,Male,Health and beauty,58.15,4,11.6300,244.2300,1/23/2019,17:44,Cash,232.60,4.761905,11.6300,8.4
983,148-41-7930,C,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.9860,734.7060,1/23/2019,10:33,Cash,699.72,4.761905,34.9860,6.1
984,189-40-5216,C,Naypyitaw,Normal,Male,Electronic accessories,96.37,7,33.7295,708.3195,1/9/2019,11:40,Cash,674.59,4.761905,33.7295,6.0
985,374-38-5555,B,Mandalay,Normal,Female,Fashion accessories,63.71,5,15.9275,334.4775,2/7/2019,19:30,Ewallet,318.55,4.761905,15.9275,8.5
986,764-44-8999,B,Mandalay,Normal,Female,Health and beauty,14.76,2,1.4760,30.9960,2/18/2019,14:42,Ewallet,29.52,4.761905,1.4760,4.3
990,886-18-2897,A,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,19:06,Credit card,282.80,4.761905,14.1400,4.5
991,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,18:10,Ewallet,766.00,4.761905,38.3000,6.0
992,745-74-0715,A,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,20:46,Ewallet,116.06,4.761905,5.8030,8.8
993,690-01-6631,B,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,18:35,Ewallet,174.90,4.761905,8.7450,6.6
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1

In [53]:
df.groupby("Product line")["Payment"].nunique()

Product line
Electronic accessories    3
Fashion accessories       3
Food and beverages        3
Health and beauty         3
Home and lifestyle        3
Sports and travel         3
Name: Payment, dtype: int64

df.groupby("")

In [54]:
df.groupby("Product line")["Gender"].nunique()

Product line
Electronic accessories    2
Fashion accessories       2
Food and beverages        2
Health and beauty         2
Home and lifestyle        2
Sports and travel         2
Name: Gender, dtype: int64

In [59]:
Eletronics = df.loc[df["Product line"] == "Electronic accessories"]
Eletronics.loc[Eletronics["Gender"] == "Male"].shape

(86, 17)

In [61]:
Eletronics.loc[Eletronics["Gender"] == "Female"].shape

(84, 17)

In [63]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')

In [68]:
listaGenero = ['Male', 'Female']

for i in listaGenero:
    print('Genero: {}, Quantidade= {}'.format(i, df.loc[df["Gender"] == i].shape))

Genero: Male, Quantidade= (499, 17)
Genero: Female, Quantidade= (501, 17)

In [66]:
df["Gender"].nunique()

2

In [72]:
df.groupby("Gender")["Quantity"].nunique()

Gender
Female    10
Male      10
Name: Quantity, dtype: int64