In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("supermarket_sales - Sheet1.csv")

In [3]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [4]:
df["Payment"].max()

'Ewallet'

In [6]:
df.min()

Invoice ID                            101-17-6199
Branch                                          A
City                                     Mandalay
Customer type                              Member
Gender                                     Female
Product line               Electronic accessories
Unit price                                  10.08
Quantity                                        1
Tax 5%                                     0.5085
Total                                     10.6785
Date                                     1/1/2019
Time                                        10:00
Payment                                      Cash
cogs                                        10.17
gross margin percentage                    4.7619
gross income                               0.5085
Rating                                          4
dtype: object

In [8]:
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [9]:
pd.read_json("municipios-geo.json")

                                               features               type
0     {'geometry': {'coordinates': [[[[-51.058868, -...  FeatureCollection
1     {'geometry': {'coordinates': [[[[-49.983663, -...  FeatureCollection
2     {'geometry': {'coordinates': [[[[-50.037259, -...  FeatureCollection
3     {'geometry': {'coordinates': [[[[-56.306636, -...  FeatureCollection
4     {'geometry': {'coordinates': [[[[-62.274769, -...  FeatureCollection
5     {'geometry': {'coordinates': [[[[-36.284752, -...  FeatureCollection
6     {'geometry': {'coordinates': [[[[-35.369598, -...  FeatureCollection
7     {'geometry': {'coordinates': [[[[-50.470596, -...  FeatureCollection
8     {'geometry': {'coordinates': [[[[-41.787473, -...  FeatureCollection
9     {'geometry': {'coordinates': [[[[-46.041821, -...  FeatureCollection
10    {'geometry': {'coordinates': [[[[-44.447747, -...  FeatureCollection
11    {'geometry': {'coordinates': [[[[-43.312696, -...  FeatureCollection
12    {'geometry': {'coordinates': [[[[-48.422407, -...  FeatureCollection
13    {'geometry': {'coordinates': [[[[-52.040093, -...  FeatureCollection
14    {'geometry': {'coordinates': [[[[-41.192332, -...  FeatureCollection
15    {'geometry': {'coordinates': [[[[-48.881553, -...  FeatureCollection
16    {'geometry': {'coordinates': [[[[-57.475784, -...  FeatureCollection
17    {'geometry': {'coordinates': [[[[-51.089441, -...  FeatureCollection
18    {'geometry': {'coordinates': [[[[-50.139055, -...  FeatureCollection
19    {'geometry': {'coordinates': [[[[-35.623419, -...  FeatureCollection
20    {'geometry': {'coordinates': [[[[-35.529694, -...  FeatureCollection
21    {'geometry': {'coordinates': [[[[-35.323235, -...  FeatureCollection
22    {'geometry': {'coordinates': [[[[-48.796564, -...  FeatureCollection
23    {'geometry': {'coordinates': [[[[-47.925746, -...  FeatureCollection
24    {'geometry': {'coordinates': [[[[-52.535127, -...  FeatureCollection
25    {'geometry': {'coordinates': [[[[-47.153868, -...  FeatureCollection
26    {'geometry': {'coordinates': [[[[-37.326219, -...  FeatureCollection
27    {'geometry': {'coordinates': [[[[-67.343534, -...  FeatureCollection
28    {'geometry': {'coordinates': [[[[-54.515516, -...  FeatureCollection
29    {'geometry': {'coordinates': [[[[-59.248117, -...  FeatureCollection
...                                                 ...                ...
5540  {'geometry': {'coordinates': [[[[-45.291739, -...  FeatureCollection
5541  {'geometry': {'coordinates': [[[[-51.737525, -...  FeatureCollection
5542  {'geometry': {'coordinates': [[[[-41.453356, -...  FeatureCollection
5543  {'geometry': {'coordinates': [[[[-35.65029, -8...  FeatureCollection
5544  {'geometry': {'coordinates': [[[[-44.069147, -...  FeatureCollection
5545  {'geometry': {'coordinates': [[[[-44.124519, -...  FeatureCollection
5546  {'geometry': {'coordinates': [[[[-53.777672, -...  FeatureCollection
5547  {'geometry': {'coordinates': [[[[-45.550187, -...  FeatureCollection
5548  {'geometry': {'coordinates': [[[[-36.413064, -...  FeatureCollection
5549  {'geometry': {'coordinates': [[[[-45.506528, -...  FeatureCollection
5550  {'geometry': {'coordinates': [[[[-44.69374, -4...  FeatureCollection
5551  {'geometry': {'coordinates': [[[[-51.048066, -...  FeatureCollection
5552  {'geometry': {'coordinates': [[[[-48.771776, -...  FeatureCollection
5553  {'geometry': {'coordinates': [[[[-47.260914, -...  FeatureCollection
5554  {'geometry': {'coordinates': [[[[-45.754268, -...  FeatureCollection
5555  {'geometry': {'coordinates': [[[[-35.363676, -...  FeatureCollection
5556  {'geometry': {'coordinates': [[[[-50.315516, -...  FeatureCollection
5557  {'geometry': {'coordinates': [[[[-49.281556, -...  FeatureCollection
5558  {'geometry': {'coordinates': [[[[-48.729571, -...  FeatureCollection
5559  {'geometry': {'coordinates': [[[[-42.004962, -...  FeatureCollection
5560  {'geometry': {'coordinates': [[[[-46.872288, -...  FeatureCollection
5561  {'geometry': {'coordinates': [[[[-49.907135, -...  FeatureCollection
5562  {'geometry': {'coordinates': [[[[-49.489881, -...  FeatureCollection
5563  {'geometry': {'coordinates': [[[[-48.951034, -...  FeatureCollection
5564  {'geometry': {'coordinates': [[[[-50.742503, -...  FeatureCollection
5565  {'geometry': {'coordinates': [[[[-44.839182, -...  FeatureCollection
5566  {'geometry': {'coordinates': [[[[-42.687166, -...  FeatureCollection
5567  {'geometry': {'coordinates': [[[[-49.367764, -...  FeatureCollection
5568  {'geometry': {'coordinates': [[[[-53.261645, -...  FeatureCollection
5569  {'geometry': {'coordinates': [[[[-38.960895, -...  FeatureCollection

[5570 rows x 2 columns]

In [10]:
mun = pd.read_json("municipios-geo.json")

In [11]:
mun.head()

                                            features               type
0  {'geometry': {'coordinates': [[[[-51.058868, -...  FeatureCollection
1  {'geometry': {'coordinates': [[[[-49.983663, -...  FeatureCollection
2  {'geometry': {'coordinates': [[[[-50.037259, -...  FeatureCollection
3  {'geometry': {'coordinates': [[[[-56.306636, -...  FeatureCollection
4  {'geometry': {'coordinates': [[[[-62.274769, -...  FeatureCollection

In [12]:
df = pd.read_csv("supermarket_sales - Sheet1.csv")

In [13]:
dt = pd.read_csv("sales_data_sample.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 8: invalid start byte

In [14]:
df = pd.read_csv("supermarket_sales - Sheet1.csv")

In [15]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [16]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,A,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,17:15,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9
10,351-62-0822,B,Mandalay,Member,Female,Fashion accessories,14.48,4,2.8960,60.8160,2/6/2019,18:07,Ewallet,57.92,4.761905,2.8960,4.5
11,529-56-3974,B,Mandalay,Member,Male,Electronic accessories,25.51,4,5.1020,107.1420,3/9/2019,17:03,Cash,102.04,4.761905,5.1020,6.8
12,365-64-0515,A,Yangon,Normal,Female,Electronic accessories,46.95,5,11.7375,246.4875,2/12/2019,10:25,Ewallet,234.75,4.761905,11.7375,7.1
13,252-56-2699,A,Yangon,Normal,Male,Food and beverages,43.19,10,21.5950,453.4950,2/7/2019,16:48,Ewallet,431.90,4.761905,21.5950,8.2
14,829-34-3910,A,Yangon,Normal,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,19:21,Cash,713.80,4.761905,35.6900,5.7
15,299-46-1805,B,Mandalay,Member,Female,Sports and travel,93.72,6,28.1160,590.4360,1/15/2019,16:19,Cash,562.32,4.761905,28.1160,4.5
16,656-95-9349,A,Yangon,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,3/11/2019,11:03,Credit card,482.51,4.761905,24.1255,4.6
17,765-26-6951,A,Yangon,Normal,Male,Sports and travel,72.61,6,21.7830,457.4430,1/1/2019,10:39,Credit card,435.66,4.761905,21.7830,6.9
18,329-62-1586,A,Yangon,Normal,Male,Food and beverages,54.67,3,8.2005,172.2105,1/21/2019,18:00,Credit card,164.01,4.761905,8.2005,8.6
19,319-50-3348,B,Mandalay,Normal,Female,Home and lifestyle,40.30,2,4.0300,84.6300,3/11/2019,15:30,Ewallet,80.60,4.761905,4.0300,4.4
20,300-71-4605,C,Naypyitaw,Member,Male,Electronic accessories,86.04,5,21.5100,451.7100,2/25/2019,11:24,Ewallet,430.20,4.761905,21.5100,4.8
21,371-85-5789,B,Mandalay,Normal,Male,Health and beauty,87.98,3,13.1970,277.1370,3/5/2019,10:40,Ewallet,263.94,4.761905,13.1970,5.1
22,273-16-6619,B,Mandalay,Normal,Male,Home and lifestyle,33.20,2,3.3200,69.7200,3/15/2019,12:20,Credit card,66.40,4.761905,3.3200,4.4
23,636-48-8204,A,Yangon,Normal,Male,Electronic accessories,34.56,5,8.6400,181.4400,2/17/2019,11:15,Ewallet,172.80,4.761905,8.6400,9.9
24,549-59-1358,A,Yangon,Member,Male,Sports and travel,88.63,3,13.2945,279.1845,3/2/2019,17:36,Ewallet,265.89,4.761905,13.2945,6.0
25,227-03-5010,A,Yangon,Member,Female,Home and lifestyle,52.59,8,21.0360,441.7560,3/22/2019,19:20,Credit card,420.72,4.761905,21.0360,8.5
26,649-29-6775,B,Mandalay,Normal,Male,Fashion accessories,33.52,1,1.6760,35.1960,2/8/2019,15:31,Cash,33.52,4.761905,1.6760,6.7
27,189-17-4241,A,Yangon,Normal,Female,Fashion accessories,87.67,2,8.7670,184.1070,3/10/2019,12:17,Credit card,175.34,4.761905,8.7670,7.7
28,145-94-9061,B,Mandalay,Normal,Female,Food and beverages,88.36,5,22.0900,463.8900,1/25/2019,19:48,Cash,441.80,4.761905,22.0900,9.6
29,848-62-7243,A,Yangon,Normal,Male,Health and beauty,24.89,9,11.2005,235.2105,3/15/2019,15:36,Cash,224.01,4.761905,11.2005,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,746-04-1077,B,Mandalay,Member,Female,Food and beverages,84.63,10,42.3150,888.6150,1/1/2019,11:36,Credit card,846.30,4.761905,42.3150,9.0
971,448-34-8700,B,Mandalay,Member,Male,Home and lifestyle,36.91,7,12.9185,271.2885,2/10/2019,13:51,Ewallet,258.37,4.761905,12.9185,6.7
972,452-04-8808,B,Mandalay,Normal,Male,Electronic accessories,87.08,7,30.4780,640.0380,1/26/2019,15:17,Cash,609.56,4.761905,30.4780,5.5
973,531-56-4728,A,Yangon,Normal,Male,Home and lifestyle,80.08,3,12.0120,252.2520,2/11/2019,15:29,Cash,240.24,4.761905,12.0120,5.4
974,744-82-9138,C,Naypyitaw,Normal,Male,Fashion accessories,86.13,2,8.6130,180.8730,2/7/2019,17:59,Cash,172.26,4.761905,8.6130,8.2
975,883-69-1285,B,Mandalay,Member,Male,Fashion accessories,49.92,2,4.9920,104.8320,3/6/2019,11:55,Credit card,99.84,4.761905,4.9920,7.0
976,221-25-5073,A,Yangon,Normal,Female,Food and beverages,74.66,4,14.9320,313.5720,3/4/2019,10:39,Cash,298.64,4.761905,14.9320,8.5
977,518-71-6847,B,Mandalay,Member,Male,Food and beverages,26.60,6,7.9800,167.5800,2/26/2019,15:10,Ewallet,159.60,4.761905,7.9800,4.9
978,156-20-0370,B,Mandalay,Normal,Female,Electronic accessories,25.45,1,1.2725,26.7225,3/10/2019,18:10,Credit card,25.45,4.761905,1.2725,5.1
979,151-33-7434,B,Mandalay,Normal,Female,Food and beverages,67.77,1,3.3885,71.1585,2/4/2019,20:43,Credit card,67.77,4.761905,3.3885,6.5
980,728-47-9078,C,Naypyitaw,Member,Male,Food and beverages,59.59,4,11.9180,250.2780,1/19/2019,12:46,Cash,238.36,4.761905,11.9180,9.8
981,809-46-1866,A,Yangon,Normal,Male,Health and beauty,58.15,4,11.6300,244.2300,1/23/2019,17:44,Cash,232.60,4.761905,11.6300,8.4
982,139-32-4183,A,Yangon,Member,Female,Sports and travel,97.48,9,43.8660,921.1860,3/14/2019,14:19,Ewallet,877.32,4.761905,43.8660,7.4
983,148-41-7930,C,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.9860,734.7060,1/23/2019,10:33,Cash,699.72,4.761905,34.9860,6.1
984,189-40-5216,C,Naypyitaw,Normal,Male,Electronic accessories,96.37,7,33.7295,708.3195,1/9/2019,11:40,Cash,674.59,4.761905,33.7295,6.0
985,374-38-5555,B,Mandalay,Normal,Female,Fashion accessories,63.71,5,15.9275,334.4775,2/7/2019,19:30,Ewallet,318.55,4.761905,15.9275,8.5
986,764-44-8999,B,Mandalay,Normal,Female,Health and beauty,14.76,2,1.4760,30.9960,2/18/2019,14:42,Ewallet,29.52,4.761905,1.4760,4.3
987,552-44-5977,B,Mandalay,Member,Male,Health and beauty,62.00,8,24.8000,520.8000,1/3/2019,19:08,Credit card,496.00,4.761905,24.8000,6.2
988,267-62-7380,C,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,19:12,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,B,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,15:46,Credit card,602.96,4.761905,30.1480,8.4
990,886-18-2897,A,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,19:06,Credit card,282.80,4.761905,14.1400,4.5
991,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,18:10,Ewallet,766.00,4.761905,38.3000,6.0
992,745-74-0715,A,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,20:46,Ewallet,116.06,4.761905,5.8030,8.8
993,690-01-6631,B,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,18:35,Ewallet,174.90,4.761905,8.7450,6.6
994,652-49-6720,C,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40,Ewallet,60.95,4.761905,3.0475,5.9
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [17]:
df.tail()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [18]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

df.max()

In [20]:
df.min()

Invoice ID                            101-17-6199
Branch                                          A
City                                     Mandalay
Customer type                              Member
Gender                                     Female
Product line               Electronic accessories
Unit price                                  10.08
Quantity                                        1
Tax 5%                                     0.5085
Total                                     10.6785
Date                                     1/1/2019
Time                                        10:00
Payment                                      Cash
cogs                                        10.17
gross margin percentage                    4.7619
gross income                               0.5085
Rating                                          4
dtype: object

In [21]:
df["Total"].max()

1042.6500000000001

In [22]:
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [23]:
df.groupby("City")["Total"].sum()

City
Mandalay     106197.6720
Naypyitaw    110568.7065
Yangon       106200.3705
Name: Total, dtype: float64

In [24]:
df.groupby("City", "Payment")["Total"].sum()

ValueError: No axis named Payment for object type <class 'pandas.core.frame.DataFrame'>

In [25]:
df.groupby("City")("Payment")["Total"].sum()

TypeError: 'DataFrameGroupBy' object is not callable

In [26]:
df.groupby("Payment")["Total"].sum()

Payment
Cash           112206.570
Credit card    100767.072
Ewallet        109993.107
Name: Total, dtype: float64

In [27]:
df.groupby("Date")["Payment"]

In [28]:
df.groupby("Date")["Payment"].head()

0          Ewallet
1             Cash
2      Credit card
3          Ewallet
4          Ewallet
5          Ewallet
6          Ewallet
7          Ewallet
8      Credit card
9      Credit card
10         Ewallet
11            Cash
12         Ewallet
13         Ewallet
14            Cash
15            Cash
16     Credit card
17     Credit card
18     Credit card
19         Ewallet
20         Ewallet
21         Ewallet
22     Credit card
23         Ewallet
24         Ewallet
25     Credit card
26            Cash
27     Credit card
28            Cash
29            Cash
          ...
603        Ewallet
609        Ewallet
612           Cash
624           Cash
633        Ewallet
640        Ewallet
643    Credit card
644        Ewallet
645        Ewallet
649           Cash
654    Credit card
657        Ewallet
663    Credit card
664           Cash
675           Cash
676    Credit card
682        Ewallet
698    Credit card
710           Cash
712        Ewallet
731        Ewallet
760    Credit card
780           Cash
805           Cash
832           Cash
836        Ewallet
862    Credit card
878    Credit card
890           Cash
986        Ewallet
Name: Payment, dtype: object

In [29]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [34]:
df.groupby("Date")["Total"].sum().sort_values(by="Total", ascending=False).head(10)

TypeError: sort_values() got an unexpected keyword argument 'by'

In [32]:
df.groupby("Date")["Total"].sum()

Date
1/1/2019     4745.1810
1/10/2019    3560.9490
1/11/2019    2114.9625
1/12/2019    5184.7635
1/13/2019    2451.2040
1/14/2019    3966.6165
1/15/2019    5944.2600
1/16/2019    4289.0820
1/17/2019    3142.7550
1/18/2019    2780.4735
1/19/2019    4914.7245
1/2/2019     1945.5030
1/20/2019    3655.4490
1/21/2019    2392.0995
1/22/2019    1704.7695
1/23/2019    5994.1875
1/24/2019    5402.0505
1/25/2019    4700.3670
1/26/2019    4457.5125
1/27/2019    4635.8970
1/28/2019    4999.7115
1/29/2019    3516.5655
1/3/2019     2078.1285
1/30/2019    2558.2620
1/31/2019    5232.4965
1/4/2019     1623.6885
1/5/2019     3536.6835
1/6/2019     3614.2050
1/7/2019     2834.2440
1/8/2019     5293.7325
               ...
3/1/2019     2634.3660
3/10/2019    3163.2300
3/11/2019    2961.2520
3/12/2019    3677.5515
3/13/2019    2063.6070
3/14/2019    7214.6340
3/15/2019    2942.4150
3/16/2019    3154.4730
3/17/2019    1976.2890
3/18/2019    1292.8335
3/19/2019    5740.3920
3/2/2019     6560.3055
3/20/2019    5458.2045
3/21/2019    1877.5155
3/22/2019    3179.1480
3/23/2019    4095.0420
3/24/2019    3477.4635
3/25/2019    2272.9665
3/26/2019    1962.5130
3/27/2019    2902.8195
3/28/2019    2229.4020
3/29/2019    4023.2430
3/3/2019     4853.1735
3/30/2019    4487.0595
3/4/2019     3894.4395
3/5/2019     6230.8785
3/6/2019     3092.5965
3/7/2019     1438.2585
3/8/2019     3125.3880
3/9/2019     7474.0470
Name: Total, dtype: float64

In [33]:
df.sorted_values(by="Total").head()

AttributeError: 'DataFrame' object has no attribute 'sorted_values'

In [35]:
df.groupby("Date")["Total"].sum().sort_values(by="Total", ascending=False).head(10)

TypeError: sort_values() got an unexpected keyword argument 'by'

In [36]:
df.groupby("Date").head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,A,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,17:15,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9
10,351-62-0822,B,Mandalay,Member,Female,Fashion accessories,14.48,4,2.8960,60.8160,2/6/2019,18:07,Ewallet,57.92,4.761905,2.8960,4.5
11,529-56-3974,B,Mandalay,Member,Male,Electronic accessories,25.51,4,5.1020,107.1420,3/9/2019,17:03,Cash,102.04,4.761905,5.1020,6.8
12,365-64-0515,A,Yangon,Normal,Female,Electronic accessories,46.95,5,11.7375,246.4875,2/12/2019,10:25,Ewallet,234.75,4.761905,11.7375,7.1
13,252-56-2699,A,Yangon,Normal,Male,Food and beverages,43.19,10,21.5950,453.4950,2/7/2019,16:48,Ewallet,431.90,4.761905,21.5950,8.2
14,829-34-3910,A,Yangon,Normal,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,19:21,Cash,713.80,4.761905,35.6900,5.7
15,299-46-1805,B,Mandalay,Member,Female,Sports and travel,93.72,6,28.1160,590.4360,1/15/2019,16:19,Cash,562.32,4.761905,28.1160,4.5
16,656-95-9349,A,Yangon,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,3/11/2019,11:03,Credit card,482.51,4.761905,24.1255,4.6
17,765-26-6951,A,Yangon,Normal,Male,Sports and travel,72.61,6,21.7830,457.4430,1/1/2019,10:39,Credit card,435.66,4.761905,21.7830,6.9
18,329-62-1586,A,Yangon,Normal,Male,Food and beverages,54.67,3,8.2005,172.2105,1/21/2019,18:00,Credit card,164.01,4.761905,8.2005,8.6
19,319-50-3348,B,Mandalay,Normal,Female,Home and lifestyle,40.30,2,4.0300,84.6300,3/11/2019,15:30,Ewallet,80.60,4.761905,4.0300,4.4
20,300-71-4605,C,Naypyitaw,Member,Male,Electronic accessories,86.04,5,21.5100,451.7100,2/25/2019,11:24,Ewallet,430.20,4.761905,21.5100,4.8
21,371-85-5789,B,Mandalay,Normal,Male,Health and beauty,87.98,3,13.1970,277.1370,3/5/2019,10:40,Ewallet,263.94,4.761905,13.1970,5.1
22,273-16-6619,B,Mandalay,Normal,Male,Home and lifestyle,33.20,2,3.3200,69.7200,3/15/2019,12:20,Credit card,66.40,4.761905,3.3200,4.4
23,636-48-8204,A,Yangon,Normal,Male,Electronic accessories,34.56,5,8.6400,181.4400,2/17/2019,11:15,Ewallet,172.80,4.761905,8.6400,9.9
24,549-59-1358,A,Yangon,Member,Male,Sports and travel,88.63,3,13.2945,279.1845,3/2/2019,17:36,Ewallet,265.89,4.761905,13.2945,6.0
25,227-03-5010,A,Yangon,Member,Female,Home and lifestyle,52.59,8,21.0360,441.7560,3/22/2019,19:20,Credit card,420.72,4.761905,21.0360,8.5
26,649-29-6775,B,Mandalay,Normal,Male,Fashion accessories,33.52,1,1.6760,35.1960,2/8/2019,15:31,Cash,33.52,4.761905,1.6760,6.7
27,189-17-4241,A,Yangon,Normal,Female,Fashion accessories,87.67,2,8.7670,184.1070,3/10/2019,12:17,Credit card,175.34,4.761905,8.7670,7.7
28,145-94-9061,B,Mandalay,Normal,Female,Food and beverages,88.36,5,22.0900,463.8900,1/25/2019,19:48,Cash,441.80,4.761905,22.0900,9.6
29,848-62-7243,A,Yangon,Normal,Male,Health and beauty,24.89,9,11.2005,235.2105,3/15/2019,15:36,Cash,224.01,4.761905,11.2005,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603,642-30-6693,B,Mandalay,Normal,Female,Sports and travel,54.51,6,16.3530,343.4130,3/17/2019,13:54,Ewallet,327.06,4.761905,16.3530,7.8
609,349-97-8902,B,Mandalay,Member,Male,Food and beverages,57.89,2,5.7890,121.5690,1/17/2019,10:37,Ewallet,115.78,4.761905,5.7890,8.9
612,789-23-8625,B,Mandalay,Member,Male,Fashion accessories,93.22,3,13.9830,293.6430,1/24/2019,11:45,Cash,279.66,4.761905,13.9830,7.2
624,598-06-7312,B,Mandalay,Member,Male,Fashion accessories,91.35,1,4.5675,95.9175,2/16/2019,15:42,Cash,91.35,4.761905,4.5675,6.8
633,420-04-7590,B,Mandalay,Normal,Male,Home and lifestyle,99.70,3,14.9550,314.0550,3/18/2019,11:29,Ewallet,299.10,4.761905,14.9550,4.7
640,695-09-5146,B,Mandalay,Member,Female,Food and beverages,98.79,3,14.8185,311.1885,2/23/2019,20:00,Ewallet,296.37,4.761905,14.8185,6.4
643,131-15-8856,C,Naypyitaw,Member,Female,Food and beverages,72.52,8,29.0080,609.1680,3/30/2019,19:26,Credit card,580.16,4.761905,29.0080,4.0
644,273-84-2164,C,Naypyitaw,Member,Male,Electronic accessories,12.05,5,3.0125,63.2625,2/16/2019,15:53,Ewallet,60.25,4.761905,3.0125,5.5
645,706-36-6154,A,Yangon,Member,Male,Home and lifestyle,19.36,9,8.7120,182.9520,1/18/2019,18:43,Ewallet,174.24,4.761905,8.7120,8.7
649,740-11-5257,C,Naypyitaw,Normal,Male,Electronic accessories,24.74,10,12.3700,259.7700,2/24/2019,16:44,Cash,247.40,4.761905,12.3700,7.1
654,133-77-3154,B,Mandalay,Member,Male,Fashion accessories,60.18,4,12.0360,252.7560,2/16/2019,18:04,Credit card,240.72,4.761905,12.0360,9.4
657,562-12-5430,A,Yangon,Member,Female,Fashion accessories,88.15,3,13.2225,277.6725,1/18/2019,10:11,Ewallet,264.45,4.761905,13.2225,7.9
663,641-51-2661,C,Naypyitaw,Member,Female,Food and beverages,87.10,10,43.5500,914.5500,2/12/2019,14:45,Credit card,871.00,4.761905,43.5500,9.9
664,714-02-3114,C,Naypyitaw,Normal,Female,Sports and travel,98.80,2,9.8800,207.4800,2/21/2019,11:39,Cash,197.60,4.761905,9.8800,7.7
675,242-11-3142,B,Mandalay,Member,Male,Fashion accessories,83.77,2,8.3770,175.9170,2/24/2019,19:57,Cash,167.54,4.761905,8.3770,4.6
676,752-23-3760,B,Mandalay,Member,Female,Sports and travel,64.08,7,22.4280,470.9880,2/19/2019,19:29,Credit card,448.56,4.761905,22.4280,7.3
682,370-96-0655,C,Naypyitaw,Normal,Female,Fashion accessories,49.32,6,14.7960,310.7160,1/9/2019,13:46,Ewallet,295.92,4.761905,14.7960,7.1
698,868-06-0466,A,Yangon,Member,Male,Electronic accessories,69.58,9,31.3110,657.5310,2/19/2019,19:38,Credit card,626.22,4.761905,31.3110,7.8
710,786-94-2700,A,Yangon,Member,Male,Food and beverages,80.62,6,24.1860,507.9060,2/28/2019,20:18,Cash,483.72,4.761905,24.1860,9.1
712,183-21-3799,C,Naypyitaw,Normal,Female,Electronic accessories,77.63,9,34.9335,733.6035,2/19/2019,15:14,Ewallet,698.67,4.761905,34.9335,7.2
731,635-28-5728,A,Yangon,Normal,Male,Health and beauty,56.00,3,8.4000,176.4000,2/28/2019,19:33,Ewallet,168.00,4.761905,8.4000,4.8
760,842-40-8179,B,Mandalay,Member,Female,Food and beverages,77.20,10,38.6000,810.6000,2/11/2019,10:38,Credit card,772.00,4.761905,38.6000,5.6
780,629-42-4133,C,Naypyitaw,Normal,Male,Health and beauty,21.80,8,8.7200,183.1200,2/19/2019,19:24,Cash,174.40,4.761905,8.7200,8.3
805,220-68-6701,A,Yangon,Normal,Female,Home and lifestyle,77.47,4,15.4940,325.3740,3/17/2019,16:36,Cash,309.88,4.761905,15.4940,4.2
832,343-75-9322,B,Mandalay,Member,Female,Sports and travel,11.85,8,4.7400,99.5400,1/9/2019,16:34,Cash,94.80,4.761905,4.7400,4.1
836,288-62-1085,A,Yangon,Member,Male,Fashion accessories,38.54,5,9.6350,202.3350,1/9/2019,13:34,Ewallet,192.70,4.761905,9.6350,5.6
862,152-03-4217,B,Mandalay,Normal,Female,Home and lifestyle,11.28,9,5.0760,106.5960,3/17/2019,11:55,Credit card,101.52,4.761905,5.0760,4.3
878,448-61-3783,A,Yangon,Normal,Female,Electronic accessories,90.02,8,36.0080,756.1680,3/21/2019,16:08,Credit card,720.16,4.761905,36.0080,4.5
890,389-70-2397,C,Naypyitaw,Normal,Female,Health and beauty,83.66,5,20.9150,439.2150,2/21/2019,10:26,Cash,418.30,4.761905,20.9150,7.2
986,764-44-8999,B,Mandalay,Normal,Female,Health and beauty,14.76,2,1.4760,30.9960,2/18/2019,14:42,Ewallet,29.52,4.761905,1.4760,4.3

In [37]:
df.groupby("Date")

df.sort_values(by="Total", ascending=False).head()

In [39]:
df.groupby("Payment")["Total"].sum()

Payment
Cash           112206.570
Credit card    100767.072
Ewallet        109993.107
Name: Total, dtype: float64

In [40]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [41]:
df.Date

0       1/5/2019
1       3/8/2019
2       3/3/2019
3      1/27/2019
4       2/8/2019
5      3/25/2019
6      2/25/2019
7      2/24/2019
8      1/10/2019
9      2/20/2019
10      2/6/2019
11      3/9/2019
12     2/12/2019
13      2/7/2019
14     3/29/2019
15     1/15/2019
16     3/11/2019
17      1/1/2019
18     1/21/2019
19     3/11/2019
20     2/25/2019
21      3/5/2019
22     3/15/2019
23     2/17/2019
24      3/2/2019
25     3/22/2019
26      2/8/2019
27     3/10/2019
28     1/25/2019
29     3/15/2019
         ...
970     1/1/2019
971    2/10/2019
972    1/26/2019
973    2/11/2019
974     2/7/2019
975     3/6/2019
976     3/4/2019
977    2/26/2019
978    3/10/2019
979     2/4/2019
980    1/19/2019
981    1/23/2019
982    3/14/2019
983    1/23/2019
984     1/9/2019
985     2/7/2019
986    2/18/2019
987     1/3/2019
988    3/29/2019
989    1/28/2019
990    3/22/2019
991    1/24/2019
992    3/10/2019
993    2/22/2019
994    2/18/2019
995    1/29/2019
996     3/2/2019
997     2/9/2019
998    2/22/2019
999    2/18/2019
Name: Date, dtype: object